### ISSUE TITLE
Malformed file detection script

### ISSUE THREAD

**Issue by kjczarne** [kjczarne/metaframe#4]
Imagine in the context of NutritionVerse that some property that should be filled in is missing in the template file. Please provide a general and informative error handling over circumstances as such. Very much recommended to create a unit test for this. Perhaps even a couple of different examples of malformed files.

**Comment by isobarbaric** [comment]
if possible, can I have one toml file to look at so I can make sure to account for all properties there are

**Comment by kjczarne** [comment]
Sure, here is a sample file for one of our scans:

```toml
gid = 50
uid = "f1e75821-e41f-4159-9050-def0d981b648"

[item]
nutrition_subgroup = "ice cream and frozen dairy desserts"
food_type = "ice cream"
description = "Kawartha Death by Chocolate ice cream made with fresh milk and cream"

[metrics]
weight = 101
unit = "g"
ingredients = [
]

[model]
project_name = "Project11192023134625"
rgbd_file_names = [
    "50_icecream_1",
]
nutrition_facts_sources = [
    "IMG_7055",
    "IMG_7056",
    "IMG_7057"
]

texture_sources = [
    "IMG_7064",
    "IMG_7065",
    "IMG_7066",
    "IMG_7067"
]

quality = 3
quality_comments = "some minor holes near plate were filled, otherwise great detail"

[time]
started = "13:43:56"
finished = "13:57:25"
```
